import {StyleSheet} from 'react-native';
import {fonts} from './fonts.style.asset';
import rs from './responsiveSize.style.asset';
import {colors} from './colors.style.asset';

export const typographies = StyleSheet.create({
  poppinsSemiBold16: {
    fontFamily: fonts.poppins600,
    fontSize: rs(16),
    lineHeight: rs(26),
    color: colors.white,
    textAlign: 'left',
  },
  poppinsSemiBold28: {
    fontFamily: fonts.poppins600,
    fontSize: rs(28),
    lineHeight: rs(33),
    color: colors.black,
    textAlign: 'left',
  },
  poppinsSemiBold12: {
    fontFamily: fonts.poppins600,
    fontSize: rs(12),
    lineHeight: rs(18),
    color: colors.grey,
    textAlign: 'left',
  },
  poppinsSemiBold20: {
    fontFamily: fonts.poppins600,
    fontSize: rs(20),
    lineHeight: rs(24),
    color: colors.black,
    textAlign: 'left',
  },
  poppinsSemiBold24: {
    fontFamily: fonts.poppins600,
    fontSize: rs(24),
    lineHeight: rs(32),
    color: colors.black,
    textAlign: 'left',
  },
  poppinsSemiBold34: {
    fontFamily: fonts.poppins600,
    fontSize: rs(34),
    color: colors.white,
    textAlign: 'left',
  },
  poppinsSemiBold14: {
    fontFamily: fonts.poppins600,
    fontSize: rs(14),
    lineHeight: rs(21),
    color: colors.grey,
    textAlign: 'left',
  },
  poppinsSemiBold10: {
    fontFamily: fonts.poppins600,
    fontSize: rs(10),
    lineHeight: rs(19),
    color: colors.black,
    textAlign: 'left',
  },
  poppinsNormal10: {
    fontFamily: fonts.poppins400,
    fontSize: rs(10),
    lineHeight: rs(19),
    color: colors.black,
    textAlign: 'left',
  },
  poppinsNormal16: {
    fontFamily: fonts.poppins400,
    fontSize: rs(16),
    lineHeight: rs(21),
    color: colors.black,
    textAlign: 'left',
  },
  poppinsNormal12: {
    fontFamily: fonts.poppins400,
    fontSize: rs(12),
    lineHeight: rs(18),
    color: colors.grey,
    textAlign: 'left',
  },
  poppinsNormal14: {
    fontFamily: fonts.poppins400,
    fontSize: rs(14),
    lineHeight: rs(20),
    color: colors.grey,
    textAlign: 'left',
  },
  bodyText1: {
    fontFamily: fonts.poppins400,
    fontSize: rs(14),
    color: colors.grey,
    textAlign: 'left',
  },
  poppinsMedium16: {
    fontFamily: fonts.poppins500,
    fontSize: rs(16),
    lineHeight: rs(21),
    color: colors.grey,
    textAlign: 'left',
  },
  poppinsMedium20: {
    fontFamily: fonts.poppins500,
    fontSize: rs(20),
    lineHeight: rs(24),
    color: colors.grey,
    textAlign: 'left',
  },
  poppinsMedium14: {
    fontFamily: fonts.poppins500,
    fontSize: rs(14),
    lineHeight: rs(16),
    color: colors.grey,
    textAlign: 'left',
  },
  poppinsMedium12: {
    fontFamily: fonts.poppins500,
    fontSize: rs(12),
    lineHeight: rs(16),
    color: colors.grey,
    textAlign: 'left',
  },
  poppinsMedium11: {
    fontFamily: fonts.poppins500,
    fontSize: rs(11),
    lineHeight: rs(16),
    color: colors.grey,
    textAlign: 'left',
  },
  searchInput: {
    fontFamily: fonts.poppins500,
    fontSize: rs(14),
    color: colors.grey,
    textAlign: 'left',
  },
  poppinsBold16: {
    fontFamily: fonts.poppins700,
    fontSize: rs(16),
    lineHeight: rs(20),
    color: colors.white,
    textAlign: 'left',
  },
  poppinsBold12: {
    fontFamily: fonts.poppins700,
    fontSize: rs(12),
    lineHeight: rs(17),
    color: colors.white,
    textAlign: 'left',
  },
});
